// ESP-Watch-BadUSB WebFlasher — generated by FlasherForge
// Flashes over WebSerial using esptool-js (the Espressif JS port of esptool).
// The default target is the full image set from firmware/manifest.json — each
// image at its offset — so a bare chip can be flashed. A chosen .bin is treated
// as an app-only update at the configured app offset.

import { ESPLoader, Transport } from '../vendor/esptool-bundle.js';

const CFG = {
  "stepCount": 4,
  "flashStep": 3,
  "connectStep": 2,
  "holdToFlash": true,
  "flashManyDefault": false,
  "encrypted": false,
  "appOffset": 65536,
  "flashBaud": 921600,
  "romBaud": 115200,
  "flashMode": "keep",
  "flashFreq": "keep",
  "flashSize": "keep",
  "eraseAll": false,
  "compress": true
};

const $ = id => document.getElementById(id);

// ---- Log ------------------------------------------------------------------
const MAX_LOG_LINES = 500;
const pad2 = n => String(n).padStart(2, '0');
function tsNow() { const d = new Date(); return `${pad2(d.getHours())}:${pad2(d.getMinutes())}:${pad2(d.getSeconds())}`; }
function log(msg, cls) {
  const el = $('consoleOut');
  if (!el) return;
  String(msg).split('\n').forEach(part => {
    if (part === '') return;
    const line = document.createElement('div');
    const t = document.createElement('span'); t.className = 'ts'; t.textContent = `[${tsNow()}] `;
    const b = document.createElement('span'); if (cls) b.className = cls; b.textContent = part;
    line.appendChild(t); line.appendChild(b); el.appendChild(line);
  });
  while (el.childElementCount > MAX_LOG_LINES) el.removeChild(el.firstElementChild);
  el.scrollTop = el.scrollHeight;
  if (cls === 'err') openDrawer('console');
}
const espTerminal = {
  clean() {},
  writeLine(data) { log(String(data)); },
  write(data) { if (String(data).trim()) log(String(data).trim()); },
};

// ---- Drawers --------------------------------------------------------------
const DRAWERS = {};
if ($('console')) DRAWERS.console = 'btnConsole';
if ($('filesDrawer')) DRAWERS.filesDrawer = 'btnFiles';
let drawerOpener = null;
function openDrawer(id, moveFocus) {
  const keys = Object.keys(DRAWERS);
  const wasOpen = keys.some(d => $(d) && $(d).classList.contains('is-open'));
  keys.forEach(d => {
    const el = $(d), btn = $(DRAWERS[d]), on = d === id;
    if (!el) return;
    el.classList.toggle('is-open', on); el.inert = !on;
    if (btn) btn.setAttribute('aria-expanded', String(on));
  });
  if (id === 'console' && $('consoleOut')) { const out = $('consoleOut'); out.scrollTop = out.scrollHeight; }
  if (id) {
    if (!moveFocus) return;
    if (!wasOpen) drawerOpener = document.activeElement;
    const el = $(id); const close = el && el.querySelector('.x'); if (close) close.focus({ preventScroll: true });
  } else if (wasOpen && drawerOpener && document.contains(drawerOpener)) {
    drawerOpener.focus({ preventScroll: true }); drawerOpener = null;
  }
}
function closeDrawers() { openDrawer(null); }
Object.keys(DRAWERS).forEach(d => { const b = $(DRAWERS[d]); if (b) b.addEventListener('click', () => $(d).classList.contains('is-open') ? closeDrawers() : openDrawer(d, true)); });
document.querySelectorAll('[data-close]').forEach(b => b.addEventListener('click', closeDrawers));
document.addEventListener('keydown', e => { if (e.key === 'Escape') closeDrawers(); });

// ---- Wizard ---------------------------------------------------------------
const LAST_STEP = CFG.stepCount;          // index of the terminal "done" view
const FLASH_STEP = CFG.flashStep;
const CONNECT_STEP = CFG.connectStep;
const DONE_STEP = CFG.stepCount;
let step = 0;
const views = [...document.querySelectorAll('.view')];
const rail  = [...document.querySelectorAll('#rail li')];

function syncRail(n) {
  rail.forEach(li => {
    const i = +li.dataset.step;
    const current = i === n && n < LAST_STEP;
    li.classList.toggle('on', current);
    li.classList.toggle('done', i < n);
    let fill; if (i < n) fill = 100; else if (current) fill = Math.round((n + 1) / rail.length * 100); else fill = 0;
    li.style.setProperty('--fill', fill);
    if (current) li.setAttribute('aria-current', 'step'); else li.removeAttribute('aria-current');
    const btn = li.querySelector('.railbtn'); if (btn) btn.disabled = i >= n;
  });
}
function goTo(n) {
  if (n === step) return;
  const from = views.find(v => +v.dataset.step === step);
  const to = views.find(v => +v.dataset.step === n);
  if (!to) return;
  if (from) { from.classList.remove('is-on'); from.classList.add('is-out'); setTimeout(() => from.classList.remove('is-out'), 320); }
  to.classList.add('is-on');
  step = n; document.body.dataset.step = String(n); syncRail(n);
  const h = to.querySelector('h1'); if (h) { h.setAttribute('tabindex', '-1'); h.focus({ preventScroll: true }); }
}
document.querySelectorAll('[data-go]').forEach(b => b.addEventListener('click', () => goTo(+b.dataset.go)));
rail.forEach(li => { const btn = li.querySelector('.railbtn'); if (btn) btn.addEventListener('click', () => { if (li.classList.contains('done')) goTo(+li.dataset.step); }); });

// ---- Page-map progress ----------------------------------------------------
const MAP_MAX_CELLS = 96;
let mapCells = [];
function buildPageMap(units) {
  const wrap = $('pagemap'); if (!wrap) return;
  const n = Math.max(1, Math.min(units, MAP_MAX_CELLS));
  wrap.textContent = ''; mapCells = [];
  for (let i = 0; i < n; i++) { const c = document.createElement('i'); c.style.setProperty('--i', i); wrap.appendChild(c); mapCells.push(c); }
  wrap.classList.remove('is-done', 'is-error', 'is-erasing');
  wrap.setAttribute('aria-valuenow', '0');
}
function paintProgress(done, total) {
  const wrap = $('pagemap');
  const upto = Math.round(mapCells.length * done / (total || 1));
  for (let i = 0; i < mapCells.length; i++) { mapCells[i].classList.toggle('on', i < upto); mapCells[i].classList.toggle('next', i === upto); }
  if (wrap) wrap.setAttribute('aria-valuenow', String(Math.round(100 * done / (total || 1))));
  if ($('rdDone')) $('rdDone').textContent = Math.round(done / 1024);
  if ($('rdTotal')) $('rdTotal').textContent = Math.round(total / 1024);
}
function mapState(state) {
  const wrap = $('pagemap'); if (!wrap) return;
  wrap.classList.toggle('is-erasing', state === 'erasing');
  wrap.classList.toggle('is-done', state === 'done');
  wrap.classList.toggle('is-error', state === 'error');
  if (state) mapCells.forEach(c => c.classList.remove('next'));
  if (state === 'error') { const next = mapCells.find(c => !c.classList.contains('on')); if (next) next.classList.add('fail'); }
}
function setPhase(text) { const e = $('phase'), f = $('footStat'); if (e) e.textContent = text; if (f) f.textContent = text; }
function setStatus(text, state) {
  const l = $('statusText'), w = $('status');
  if (l) l.textContent = text; if (w) w.dataset.state = state || 'idle';
  document.body.dataset.state = state || 'idle';
}
function showFlashError(msg) { const el = $('flashErr'); if (!el) return; el.hidden = !msg; el.textContent = msg || ''; }
function showBatchNote(msg) { const el = $('batchNote'); if (!el) return; el.hidden = !msg; el.textContent = msg || ''; }

// ---- Image loading --------------------------------------------------------
const APP_OFFSET = CFG.appOffset;
function bufToBinaryString(buf) {
  const bytes = new Uint8Array(buf);
  let out = ''; const CHUNK = 0x8000;
  for (let i = 0; i < bytes.length; i += CHUNK) out += String.fromCharCode.apply(null, bytes.subarray(i, i + CHUNK));
  return out;
}
async function fetchPart(path) {
  const r = await fetch(path, { cache: 'no-store' });
  if (!r.ok) throw new Error(`${path}: HTTP ${r.status}`);
  return r.arrayBuffer();
}
// Flash-time clock blob — packed into a tiny binary that the firmware reads
// from the head of the coredump partition (0x3F0000) at boot and consumes
// once. Lays out as:
//   uint32 LE magic  0xC10CBA5E
//   uint64 LE epoch  UTC seconds at flash time
//   int32  LE tz     local timezone offset, seconds east of UTC
//   uint32 LE pad
// A 4 KiB payload keeps the erase aligned to the flash sector.
function buildClockBlob() {
  const SECTOR = 4096;
  const buf = new ArrayBuffer(SECTOR);
  const view = new DataView(buf);
  const epoch = BigInt(Math.floor(Date.now() / 1000));
  // JS getTimezoneOffset() returns MINUTES WEST of UTC. Firmware wants
  // SECONDS EAST of UTC, so negate + × 60.
  const tz = -new Date().getTimezoneOffset() * 60;
  view.setUint32 (0,  0xC10CBA5E,       true);
  view.setBigUint64(4,  epoch,          true);
  view.setInt32  (12, tz,               true);
  view.setUint32 (16, 0,                true);
  // Fill the rest with 0xFF to match erased-flash state — every byte
  // still needs writing so the target's stale magic (if any) is wiped.
  const tail = new Uint8Array(buf, 20);
  for (let i = 0; i < tail.length; i++) tail[i] = 0xFF;
  return { buf, epoch: Number(epoch), tz };
}

// Convert an ArrayBuffer to esptool.js's expected binary string form.
function bufToBinaryStr(buf) {
  const b = new Uint8Array(buf);
  let s = '';
  for (let i = 0; i < b.length; i++) s += String.fromCharCode(b[i]);
  return s;
}

async function loadManifestImages() {
  const r = await fetch('./firmware/manifest.json', { cache: 'no-store' });
  if (!r.ok) throw new Error(`manifest.json: HTTP ${r.status}`);
  const man = await r.json();
  const parts = [];
  for (const p of man.parts) {
    const buf = await fetchPart('./firmware/' + p.path);
    parts.push({ data: bufToBinaryString(buf), address: p.offset, bytes: buf.byteLength });
    log(`image: ${p.path} ${buf.byteLength} B @ 0x${p.offset.toString(16)}`);
  }
  // Clock blob at the coredump partition (0x3F0000) — huge_app.csv puts
  // 64 KiB there, we only touch the first sector.
  const clock = buildClockBlob();
  parts.push({ data: bufToBinaryStr(clock.buf), address: 0x3F0000,
               bytes: clock.buf.byteLength });
  const tzSign = clock.tz >= 0 ? '+' : '-';
  const tzHrs = Math.abs(clock.tz) / 3600;
  log(`clock: epoch=${clock.epoch} tz=${tzSign}${tzHrs.toFixed(2)}h → 0x3F0000`);
  if ($('pickName')) $('pickName').textContent = `full image · v${man.version || '?'}`;
  return parts;
}

// ---- WebSerial + esptool --------------------------------------------------
let transport = null;
let esploader = null;
let flashing = false;
let images = null;
let batchCount = 0;
function batchOn() { const cb = $('flashMany'); return !!(cb && cb.checked); }

async function connect() {
  if (!('serial' in navigator)) { log('no WebSerial here. use Chrome or Edge.', 'err'); setStatus('No WebSerial', 'error'); return; }
  const btn = $('btnConnect'); if (btn) btn.classList.add('loading');
  try {
    const port = await navigator.serial.requestPort({});
    transport = new Transport(port, true);
    esploader = new ESPLoader({ transport, baudrate: CFG.flashBaud, romBaudrate: CFG.romBaud, terminal: espTerminal, debugLogging: false });
    setStatus('Connecting', 'live');
    const chip = await esploader.main();
    log(`connect: ${chip}`, 'ok');
    if ($('pickChip')) $('pickChip').textContent = chip;
    setStatus(chip, 'ok');
    if (!images && !CFG.encrypted) { try { images = await loadManifestImages(); } catch (e) { log('images: ' + e.message, 'err'); } }
    if ($('btnFlash')) $('btnFlash').disabled = !images;
    goTo(FLASH_STEP);
  } catch (e) {
    if (e && (e.name === 'NotFoundError' || /No port selected/i.test(e.message || ''))) log('connect: no device picked');
    else { log('connect: ' + (e && e.message ? e.message : e), 'err'); setStatus('Connect failed', 'error'); }
    try { if (transport) await transport.disconnect(); } catch (_) {}
    transport = null; esploader = null;
  } finally { if (btn) btn.classList.remove('loading'); }
}
if ($('btnConnect')) $('btnConnect').onclick = connect;

if ($('fileBin')) $('fileBin').onchange = async ev => {
  const f = ev.target.files[0]; if (!f) return;
  try {
    const buf = await f.arrayBuffer();
    images = [{ data: bufToBinaryString(buf), address: APP_OFFSET, bytes: buf.byteLength }];
    if ($('pickName')) $('pickName').textContent = `${f.name} · app @ 0x${APP_OFFSET.toString(16)}`;
    log(`firmware: ${f.name}, ${buf.byteLength} B @ 0x${APP_OFFSET.toString(16)}`, 'ok');
    if ($('btnFlash')) $('btnFlash').disabled = !esploader;
  } catch (e) { log(`${f.name}: ${e.message}`, 'err'); ev.target.value = ''; }
};

async function runFlash() {
  if (!esploader) { log('flash: connect first', 'err'); return; }
  if (!images) { try { images = await loadManifestImages(); } catch (e) { log('images: ' + e.message, 'err'); return; } }

  const btn = $('btnFlash');
  if (btn) btn.disabled = true;
  flashing = true;
  mapState(null); showFlashError(null); showBatchNote(null);
  setStatus('Flashing', 'live');

  const total = images.reduce((n, p) => n + p.bytes, 0);
  const before = []; let acc = 0; for (const p of images) { before.push(acc); acc += p.bytes; }
  buildPageMap(Math.max(24, Math.round(total / 4096)));
  if ($('rdParts')) $('rdParts').textContent = `0 / ${images.length} parts`;
  paintProgress(0, total);

  try {
    setPhase('writing');
    await esploader.writeFlash({
      fileArray: images.map(p => ({ data: p.data, address: p.address })),
      flashSize: CFG.flashSize,
      flashMode: CFG.flashMode,
      flashFreq: CFG.flashFreq,
      // Watch flasher: honour the "Fully erase flash before writing" checkbox
      // — overrides the CFG default (false). Checked = erase every sector
      // first, wipes NVS + saved WiFi + stale silent_boot/bricked flags.
      eraseAll: document.getElementById('fullErase')?.checked ?? CFG.eraseAll,
      compress: CFG.compress,
      reportProgress: (fileIndex, written, fileTotal) => {
        const done = (before[fileIndex] || 0) + written;
        paintProgress(done, total);
        if ($('rdParts')) $('rdParts').textContent = `${written >= fileTotal ? fileIndex + 1 : fileIndex} / ${images.length} parts`;
      },
    });
    setPhase('resetting');
    log('flash: done, resetting', 'ok');
    try { await esploader.after('hard_reset'); } catch (_) {}
    paintProgress(total, total);
    setPhase('done'); mapState('done');
    setStatus('Flashed', 'ok');
    await onFlashSuccess();
  } catch (e) {
    const msg = (e && e.message) ? e.message : String(e);
    log('flash: ' + msg, 'err'); showFlashError(msg);
    setPhase('failed'); mapState('error');
    setStatus('Flash failed', 'error');
    if (btn) btn.disabled = false;
  } finally { flashing = false; }
}

async function onFlashSuccess() {
  batchCount++;
  if (batchOn()) {
    // Re-arm for the next device: the flashed board resets and re-enumerates,
    // so its serial port handle is now stale. Drop it and send the user back
    // to Connect to pick the next one. The image data is kept and reused.
    log(`batch: device ${batchCount} flashed. unplug it, plug the next, connect again.`, 'ok');
    try { if (transport) await transport.disconnect(); } catch (_) {}
    transport = null; esploader = null;
    if ($('btnFlash')) $('btnFlash').disabled = true;
    setStatus(`Ready · ${batchCount} done`, 'idle');
    setTimeout(() => { goTo(CONNECT_STEP); showBatchNote(`Device ${batchCount} flashed — unplug, plug in the next, then Connect.`); }, 700);
  } else {
    log('done. the device is rebooting into the new firmware.', 'ok');
    setTimeout(() => goTo(DONE_STEP), 700);
  }
}

// ---- Flash trigger: hold-to-flash or click-to-flash -----------------------
(function wireFlashTrigger() {
  const btn = $('btnFlash'); if (!btn) return;
  if (!CFG.holdToFlash) { btn.addEventListener('click', () => { if (!btn.disabled && !flashing) runFlash(); }); return; }
  const HOLD_MS = 700; let timer = null;
  function reset() { if (timer) { clearTimeout(timer); timer = null; } btn.style.setProperty('--hold-dur', '140ms'); btn.style.setProperty('--hold', '0'); }
  function begin(e) {
    if (btn.disabled || flashing || timer) return;
    if (e.cancelable) e.preventDefault();
    btn.style.setProperty('--hold-dur', HOLD_MS + 'ms'); btn.style.setProperty('--hold', '1');
    timer = setTimeout(() => { reset(); runFlash(); }, HOLD_MS);
  }
  btn.addEventListener('pointerdown', begin);
  btn.addEventListener('pointerup', reset);
  btn.addEventListener('pointerleave', reset);
  btn.addEventListener('pointercancel', reset);
  btn.addEventListener('keydown', e => { if ((e.key === 'Enter' || e.key === ' ') && !e.repeat) begin(e); });
  btn.addEventListener('keyup', e => { if (e.key === 'Enter' || e.key === ' ') reset(); });
  btn.addEventListener('blur', reset);
})();

// ---- Boot -----------------------------------------------------------------
document.body.dataset.step = '0';
syncRail(0);
setStatus('No device', 'idle');
setPhase('ready');
if (!('serial' in navigator)) {
  log('no WebSerial in this browser. use Chrome or Edge.', 'err');
  if ($('btnConnect')) $('btnConnect').disabled = true;
  setStatus('No WebSerial', 'error');
}
window.addEventListener('beforeunload', ev => { if (flashing) { ev.preventDefault(); ev.returnValue = ''; } });
